version: 2
builds:
  - skip: true
annouce:
  - skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  extra_files:
    - glob: ./dist/**/*
  name_template: "Release {{.Tag}}"
  header: |
    # What's Changed
    ## 🚀 Features
    ## 🎄 Enhancements
    ## 🐛 Bug Fixes