name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: | 
          git fetch --force --tags 
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install gcc-multilib
          sudo apt-get install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config gcc-aarch64-linux-gnu ibasound2-dev:i386 libgl1-mesa-dev:i386 libxcursor-dev:i386 libxi-dev:i386 libxinerama-dev:i386 libxrandr-dev:i386 libxxf86vm-dev:i386
      - uses: actions/setup-go@v3
        with:
          go-version: stable
          cache: true
      #- run: |
      #    sudo apt install libasound2-dev
      - uses: goreleaser/goreleaser-action@v6
        with:         
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: 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
          