name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-binary:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-windows.yml --split
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libx11-dev xserver-xorg-dev xorg-dev libx11-xcb-dev libxcb-randr0-dev libxcb1-dev 
      
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-linux.yml --split
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-darwin.yml --clean --split
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
  merge-and-release:
    needs: [build-linux-binary, build-darwin-binary, build-windows-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=build --clean --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 