name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-binary:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: go-wave-function-collapse
          path: |
            ./dist/go-wave-function-collapse*
            ./dist/checksums.txt
  
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libx11-dev xserver-xorg-dev xorg-dev libx11-xcb-dev libxcb-randr0-dev libxcb1-dev 
      
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: go-wave-function-collapse
          path: |
            ./dist/go-wave-function-collapse*
            ./dist/checksums.txt

  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: go-wave-function-collapse
          path: |
            ./dist/go-wave-function-collapse* 
            ./dist/checksums.txt 
  
  merge-and-release:
    needs: [build-linux-binary, build-darwin-binary, build-windows-binary]
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: go-wave-function-collapse
        path: ./dist/
    - name: Check directory tree
      run: tree
    - name: Set tag name
      id: tag
      run: |
        if [[ "${{ github.event_name }}" != "push" ]]; then
          tag=v$(date +%Y%m%d.%H%M%S)
        else
          tag=$(basename "${{ github.ref }}")
        fi
        echo "tag=$tag" >> $GITHUB_OUTPUT
    - name: Publish Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh release create "${{ steps.tag.outputs.tag }}" ./dist/*.zip ./dist/*.tar.gz
        gh release edit "${{ steps.tag.outputs.tag }}" --draft=false
        gh release upload "${{ steps.tag.outputs.tag }}" ./dist/*.zip ./dist/*.tar.gz
    - uses: eregon/keep-last-n-releases@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        n: 3
        remove_tags_without_release: true