
name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libxcb-dev
          sudo apt-get install gcc-multilib
          sudo apt-get install libasound2-dev:i386 libgl1-mesa-dev:i386 libxcursor-dev:i386 libxi-dev:i386 libxinerama-dev:i386 libxrandr-dev:i386 libxxf86vm-dev:i386
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: go-wave-function-collapse
          path: |
            dist/go-wave-function-collapse*
            dist/checksums.txt

  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --skip=publish --config .goreleaser-darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}    
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: go-wave-function-collapse
          path: |
            dist/go-wave-function-collapse* 
            dist/checksums.txt 
  merge-and-release:
    needs: [build-linux-binary, build-darwin-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true
      - name: Make directories
        run: |
          mkdir -p ./go-wave-function-collapse-build/linux
          mkdir -p ./go-wave-function-collapse-build/darwin
      - name: Download linux binaries
        uses: actions/download-artifact@v3
        with:
          name: go-wave-function-collapse-linux
          path: ./go-wave-function-collapse-build/linux
      - name: Download darwin binaries
        uses: actions/download-artifact@v3
        with:
          name: go-wave-function-collapse-darwin
          path: ./go-wave-function-collapse-build/darwin          
      - name: Merge checksum file
        run: |
          cd ./go-wave-function-collapse-build
          cat ./darwin/checksums.txt >> checksums.txt
          cat ./linux/checksums.txt >> checksums.txt
          rm ./darwin/checksums.txt
          rm ./linux/checksums.txt
      - name: Check git status
        run: |
          tree
          git status
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --config .goreleaser-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 